### ISSUE TITLE
ERROR - STAR command not found

### ISSUE THREAD

**Issue by Sanat-Mishra** [urmi-21/pyrpipe#12]
OSError: CommandNotFoundException encountered when running the first cookbook recipe of aligning and mapping A. Thaliana genome. (Screenshot Attached)

![Screenshot 2021-05-28 at 1 10 39 PM](https://user-images.githubusercontent.com/19981230/119948085-1c056200-bfb6-11eb-8dd3-d54d586abe9f.jpg)

**Comment by urmi-21** [comment]
Hi @Sanat-Mishra 
The `CommandNotFoundException` is thrown when tools invoked via pyrpipe are not installed or present in the path variable. Please check that you have STAR installed on your system. 
You can install STAR directly or follow the recommended tutorial on setting the conda environment https://pyrpipe.readthedocs.io/en/latest/tutorial/setup.html

Please install the required tools and try running pyrpipe again. Feel free to reopen if you still have issues.

**Comment by Sanat-Mishra** [comment]
Yes, thanks. I had installed STAR, but it was on a different path.
