### ISSUE TITLE
"ResolvePackageNotFound:" Trouble installing pyrpipe from environment.yaml into a virtual environment using conda

### ISSUE THREAD

**Issue by aaronatp** [urmi-21/pyrpipe#13]
Hi, I'm trying to install the pyrpipe package using the ```conda env create -f pyripe_environment.yaml``` command (as suggested here: https://githubmemory.com/repo/urmi-21/pyrpipe) but I'm getting a couple error messages: one is saying ```Solving environment: failed``` and the other is saying ```ResolvePackageNotFound: ``` followed by about a hundred other packages. The first dozen or so are:
```
  - boost-cpp==1.74.0=hc6e9bd1_2
  - orfipy==0.0.3=py39h7cff6ad_1
  - coloredlogs==15.0=py39hf3d152e_0
  - stringtie==2.1.4=h7e0af3c_0
  - libtool==2.4.6=h58526e2_1007
  - perl-xml-libxml==2.0132=pl526h7ec2d77_1
  - sqlite==3.35.3=h74cdb3f_0
  - wrapt==1.12.1=py39h3811e60_3
  - setuptools==52.0.0=py39h06a4308_0
  - googleapis-common-protos==1.53.0=py39hf3d152e_0
  - openblas==0.3.12=pthreads_h43bd3aa_1
  - chardet==4.0.0=py39hf3d152e_1
  - rich==10.0.1=py39hf3d152e_0
  - libpng==1.6.37=hed695b0_2
  - libstdcxx-ng==9.3.0=h6de172a_18

```
 I'm using a Mac computer and my operating system is OSX 11.5.2.

My conda configuration (obtained using the ```conda info``` command) is:
``` active environment : base
    active env location : /Users/myname/miniconda3
            shell level : 1
       user config file : /Users/myname/.condarc
 populated config files : /Users/myname/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/myname/miniconda3  (writable)
      conda av data dir : /Users/myname/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/myname/miniconda3/pkgs
                          /Users/myname/.conda/pkgs
       envs directories : /Users/myname/miniconda3/envs
                          /Users/myname/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
From what I've seen on this thread (https://github.com/Climate-Data-Science/Climate-Similarity-Metrics/issues/13) it seems like one issue might be that there are Operating System-specific dependencies in the .yaml package, and that this could be resolved by adding ```--no-builds``` to the ```conda env export -f environment.yml [here?]``` script. I am relatively new to programming but from what I've heard, I think this is something that would be run on the developer's end. I'm writing to ask if this would resolve the error I'm having, and if it wouldn't, if you could suggest some ways for me to resolve it (possibly using a command analogous to ```--no-builds``` but for ```conda env create``` instead of for ```conda env export```)?

**Comment by aaronatp** [comment]
Following Matt Thompson's answer to the question here (https://stackoverflow.com/questions/65735532/i-constantly-get-resolvepackagenotfound), I deleted the information after the single equals-signs for all of the "ResolvePackageNotFound"-dependencies and that got the number of those dependencies down to about a dozen. I then deleted the version-specifications (the information after the double equals-signs) and that got the number down to four, though I'm not exactly sure of the consequences of deleting that sort of information in the way that I have done. But anyway, that got the number of ResolvePackageNotFound dependencies down to four, which are:
```
ResolvePackageNotFound: 
  - libgcc-ng
  - libstdcxx-ng
  - _openmp_mutex
  - libgomp
```
I ran this and almost killed my computer - it said "Found conflicts! Looking for incompatible packages" and then churned out probably somewhere in the range of thousands of lines of what looked to me to be specifying various conflicts. @urmi-21 if you or anyone might be able to help me, I'd be very grateful.

If it's any help, some of the last lines are:

```
Package cutadapt conflicts for:
trim-galore==0.6.6=hdfd78af_1 -> cutadapt
cutadapt=3.3The following specifications were found to be incompatible with your system:

  - feature:/osx-64::__unix==0=0
  - feature:|@/osx-64::__unix==0=0
  - dropbox==11.4.1=pyhd8ed1ab_0 -> stone[version='>=2'] -> __unix
  - stone==3.2.1=pyhd8ed1ab_0 -> __unix

Your installed version is: 0
```
The "Package [package] conflicts for ..." part seems to be repeated much of the way through for different packages, but without looking too closely, I didn't see the osx/unix part with the dashes and indentation elsewhere I don't think.

**Comment by urmi-21** [comment]
Hi @Aaronpresser 
Thanks for trying out pyrpipe and reporting the issue. I agree environment files are not compatible with macOS due to the build versions. 
The environment was created using the command listed [here](https://pyrpipe.readthedocs.io/en/latest/tutorial/setup.html#create-a-new-conda-environment). Can you instead create an environment using:

```
conda create -n pyrpipe_0.0.5_mac -c bioconda pyrpipe star=2.7.7a sra-tools=2.10.1 stringtie=2.1.4 trim-galore=0.6.6 orfipy=0.0.3 salmon=1.4.0
```

or to make it faster use [mamba](https://anaconda.org/conda-forge/mamba) i.e.

```
mamba create -n pyrpipe_0.0.5_mac -c bioconda pyrpipe star=2.7.7a sra-tools=2.10.1 stringtie=2.1.4 trim-galore=0.6.6 orfipy=0.0.3 salmon=1.4.0
```
NOTE: the latest sra-tools gave me [issues on macos](https://github.com/biostars/biostar-handbook-issues/issues/149)
BTW depending on your requirements you can add remove these tools. I have tested this on a mac and it seems to work.  
Please let me know if it works for you.

**Comment by aaronatp** [comment]
Hey @urmi-21 thank you so much for reply, that made things a lot clearer and the code you suggested helped resolve my problem - I really appreciate it! Now, I'm really looking forward to using your package, which I understand is wonderful!
