### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:    - sra-tools=2.10.9

### ISSUE THREAD

**Issue by aguycalledankit** [urmi-21/pyrpipe#15]
Hi, I'm unable to install the required tools by using the command: conda install -c bioconda pyrpipe star=2.7.7a sra-tools=2.10.9 stringtie=2.1.4 trim-galore=0.6.6 orfipy=0.0.3 salmon=1.4.0

I added the three conda channels in the right order as you mentioned, but this is what I get each time (in MacOS):

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - sra-tools=2.10.9

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Could you please help? Thanks!

**Comment by aguycalledankit** [comment]
Similar Error in Windows:

PackagesNotFoundError: The following packages are not available from current channels:

  - star=2.7.7a
  - stringtie=2.1.4
  - orfipy=0.0.3
  - salmon=1.4.0
  - sra-tools=2.10.1

Current channels:

  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by urmi-21** [comment]
Hi @akumarbme,
Thanks for reporting this issue. I was able to reproduce this on a mac. Can you please try `sra-tools=2.11.0`. This solution worked for me. Please let me know.

**Comment by aguycalledankit** [comment]
Thanks @urmi-21 for getting back. I tried sra-tools=2.11.0 but I'm still getting the same error on Windows.

**Comment by urmi-21** [comment]
@akumarbme unfortunately most of the tools are unix based executables and so you can't execute then on windows environment. You need a UNIX like or mac OS to run pyrpipe.
