### ISSUE TITLE
Could you help me to install pyrpipe?

### ISSUE THREAD

**Issue by daschukds** [urmi-21/pyrpipe#16]
Hi.
I am trying to use pyrpipe for my RNAseq data. I am relatively new to python world.
i followed install page (https://pyrpipe.readthedocs.io/en/latest/installation.html) and setting up page (https://pyrpipe.readthedocs.io/en/latest/tutorial/setup.html).
Then I wanted to do 'pyrpipe_diagnostic build-tools'  and I got this error "pyrpipe_diagnostic: command not found"

I am not sure pyrpipe is installed correctly or the PATH does not have pyrpipe folder. 
I am testing the system by installing it on an ubuntu 20 OS in my virtual machine. 
Could you help me? 

Thank you.

**Comment by urmi-21** [comment]
Hi @daschukds can you please confirm if you installed pyrpipe via conda? Can you share the commands that you used?

**Comment by daschukds** [comment]
Hi urmi-21,
Thanks for your reply. I am a beginner to python even though I made a couple of small program with python for my research. 

Here is what I did.
My setting: windows10 home. 
1. I installed VMware and installed Ubuntu (lastest stable version).
2. installed miniconda as you suggested. I followed https://docs.conda.io/en/latest/miniconda.html. 
3. conda create -n pyrpipe python=3.8   
4. conda activate pyrpipe
5. conda install -c bioconda pyrpipe star=2.7.7a sra-tools=2.10.9 stringtie=2.1.4 trim-galore=0.6.6 orfipy=0.0.3 salmon=1.4.0
It was good upto step 5.

Now. I downloaded yaml file (https://github.com/urmi-21/pyrpipe/blob/master/pyrpipe_environment.yaml)
copy the yaml file to home folder in Ubuntu
conda env create -f pyrpipe_environment.yaml  (downloaded file has yaml exension instead of yml)
then I got error as below:

Even though I got the error, i tried to do  this line  "pyrpipe_diagnostic build-tools"
Of course it does not work.

I don't know where to go solve this error. 

Could you help me?

Thanks,




# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/ds/miniconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/home/ds/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 191, column 65:
         ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... 
                                             ^ (line: 191)

`$ /home/ds/miniconda3/bin/conda-env create -f pyrpipe_environment.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=pyrpipe
                CONDA_EXE=/home/ds/miniconda3/bin/conda
             CONDA_PREFIX=/home/ds/miniconda3/envs/pyrpipe
           CONDA_PREFIX_1=/home/ds/miniconda3
    CONDA_PROMPT_MODIFIER=(pyrpipe)
         CONDA_PYTHON_EXE=/home/ds/miniconda3/bin/python
               CONDA_ROOT=/home/ds/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/ds/miniconda3/bin:/home/ds/miniconda3/envs/pyrpipe/bin:/home/ds/
                          miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:
                          /sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : pyrpipe
    active env location : /home/ds/miniconda3/envs/pyrpipe
            shell level : 2
       user config file : /home/ds/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ds/miniconda3  (writable)
      conda av data dir : /home/ds/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ds/miniconda3/pkgs
                          /home/ds/.conda/pkgs
       envs directories : /home/ds/miniconda3/envs
                          /home/ds/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.7 Linux/5.13.0-30-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by urmi-21** [comment]
If you were able to execute step 5 pyrpipe should be installed. No need to create environment using the yaml file.
After step 5 run:
```
pyrpipe --help
```

You should see the pyrpipe help menu.

**Comment by daschukds** [comment]
When I tried pyrpipe --help, I got error "command not found"

I did: 
1. conda activate pyrpipe
2. pyrpipe --help
error: pyrpipe: command not found

I also went to the pyrpipe folder under Envs of Miniconda. I got the same error
(pyrpipe) ds@ubuntu:~/miniconda3/envs/pyrpipe$ pyrpipe --help
pyrpipe: command not found

As I see "(pyrpipe)", I think my env is set OK. but I can't find the command or right path.
Could you help me?

Thanks,

**Comment by daschukds** [comment]
I copy conda info results if it helps you to help me.

(pyrpipe) ds@ubuntu:~/miniconda3/envs/pyrpipe$ conda info

     active environment : pyrpipe
    active env location : /home/ds/miniconda3/envs/pyrpipe
            shell level : 2
       user config file : /home/ds/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ds/miniconda3  (writable)
      conda av data dir : /home/ds/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ds/miniconda3/pkgs
                          /home/ds/.conda/pkgs
       envs directories : /home/ds/miniconda3/envs
                          /home/ds/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.7 Linux/5.13.0-30-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

Thank you.

**Comment by daschukds** [comment]
Thank you.

**Comment by daschukds** [comment]
I have a simple question. I like to use spyder to check my script. I tried to use spyder under pyrpipe.  It runs well but it cannot find pyrpipe related files. how can I solve this issue? Thank you.

**Comment by urmi-21** [comment]
Hi, I think this is because the spyder environment is different than the one containing pyrpipe. You will need to install spyder under the pyrpipe conda environment and then run spyder. This may help https://docs.spyder-ide.org/current/faq.html
