### ISSUE TITLE
Salmon quantification with several srr_object

### ISSUE THREAD

**Issue by victorsanchezarevalo** [urmi-21/pyrpipe#17]
Hi

Fist of all congratulations for pyrpipe, it is a great tool!

I am trying to perform an RNA-seq analysis, however I am having problems with Salmon, I am using salmon as a pseudoalingner. So, after loading the different SRR files in a sraObject, I performed the trimming with Trimgalore, ( I don't do STAR as aligner and I directly go with Salmon). When I try to use Salmon, I obtain a quant.sf file with the values of the first SRR, and apparently the following ones are over write in the file. So, I cannot perform the quantification for multiple files.

Any idea about how to solve it, please?

Thank you very much!

Best

Victor

**Comment by urmi-21** [comment]
Hi, @victorsanchezarevalo Thanks for the positive feedback and I am happy to help you out. Could you please share what you already have tried?

**Comment by victorsanchezarevalo** [comment]
Thank you very much for your rapid response and availability!

I enclose a file with the imformation.

Best

Victor
________________________________
De: Urminder Singh ***@***.***>
Enviado: martes, 7 de junio de 2022 23:20
Para: urmi-21/pyrpipe ***@***.***>
Cc: Víctor Sánchez-Arévalo ***@***.***>; Mention ***@***.***>
Asunto: Re: [urmi-21/pyrpipe] Salmon quantification with several srr_object (Issue #17)



ATENCIÓN: Este mensaje proviene de una fuente EXTERNA a UFV. Por favor, sea cuidadoso especialmente con los enlaces y los archivos adjuntos que contenga.


Hi, @victorsanchezarevalo<https://github.com/victorsanchezarevalo> Thanks for the positive feedback and I am happy to help you out. Could you please share what you already have tried?

**Comment by victorsanchezarevalo** [comment]
[RNA_seq_2.md](https://github.com/urmi-21/pyrpipe/files/8862885/RNA_seq_2.md)
I enclose the file here, thanks!

**Comment by urmi-21** [comment]
Thanks for the details, I understand what you are trying to accomplish. To quantify a list of SRR runs via pyrpipe could be as concise as (thanks to pyrpipe's [chaining](https://pyrpipe.readthedocs.io/en/latest/tutorial/rnaseq.html) support):

```
#import required modules
from pyrpipe.qc import Trimgalore
from pyrpipe.quant import Salmon
runlist=['SRR7882629','SRR7882630', 'SRR7882631', 'SRR7882632']
workdir='./results'
# init salmon and trimgalore objects
# if salmon index doesn't exist, it creates one using the transcriptome
salmon=Salmon(index="human_data/salmon_index",transcriptome='human_tr.fa')
tgalore = Trimgalore()
# process each run
for srrid in runlist:
    sra.SRA(srrid,directory=workdir).trim(tgalore).quant(salmon)

```

Run the above script using (more info [here](https://pyrpipe.readthedocs.io/en/latest/tutorial/rnaseq.html#executing-the-pipeline)):
`python <script.py> --threads 10`

This will download fastq, trim and quantify with salmon. The quant.sf file for each SRRid will be under 

`<workdir>/<SRRid>/salmon_out/quant.sf`

Then you could merge all the quant.sf files and get the count matrix. A general, scalable version of quantification pipeline is available [here](https://github.com/urmi-21/pyrpipe/tree/master/case_studies/Covid_RNA-Seq). 
This uses Snakemake or Nextflow to quantify RNA-Seq from SRA provided in the [runids](https://github.com/urmi-21/pyrpipe/blob/master/case_studies/Covid_RNA-Seq/Snakemake/runids.txt) file, the [config.yaml](https://github.com/urmi-21/pyrpipe/blob/master/case_studies/Covid_RNA-Seq/Snakemake/config.yaml) contains tunable parameters. All tool parameters are under the params directory.

Please let me know if you have more questions.

version info:
**pyrpipe version 0.0.5**
**python version 3.8.6**
**prefetch version 2.10.9**
**salmon 1.4.0**
**trim_galore  version 0.6.6**

**Comment by victorsanchezarevalo** [comment]
I have tried with the script, with a couple of modifications because I have the SRR already downloaded in my computer.  After running the script I only have obtain a single quant.sf file:

Target files ./results/salmon_out/quant.sf already exist. 

Any idea? Could you tell me if I am doing something wrong?

Thanks a lot!

Vic

[Pyrpipe..md](https://github.com/urmi-21/pyrpipe/files/8878394/Pyrpipe.md)

**Comment by urmi-21** [comment]
Hi Vic,
This is because by default pyrpipe assumes each fastq is in its own directory and salmon output gets written to:

`<workdir>/<SRRid_directory>/salmon_out/quant.sf`

Since your fastqs are all in the same directory, the quant.sf gets overwritten. 

**The easiest solution is to separate fastq in their respective directories.**

Another way is that you can explicitly use the Salmon object to start quantification and provide the outdir.

```
for srrid in runlist:
    srrobject=sra.SRA(srrid,directory=workdir).trim(tgalore)
    thisout=<path_for_salmon_out_for_current_srrid>
    # explicitly call perform_quant
    salmon.perform_quant(srrobject,outdir=thisout)
```

Note the difference is, that instead of using *syntactic sugar* this is explicitly passing the SRA object to Salmon object's [perform_quant](https://pyrpipe.readthedocs.io/en/latest/pyrpipe.html?highlight=quant#pyrpipe.quant.Salmon.perform_quant) method. This is also what happens under the hood when SRA.quant() is called. Currently, there is no way to forward kwargs from SRA.quant() to Salmon.perform_quant() - something I could improve in future releases.

Please let me know if this solves your issue.
Thanks

**Comment by victorsanchezarevalo** [comment]
Thank you very much!

This is exactly what I was looking for.

Just a final question, Is it possible to use HTSeq instead of Stringtiie in pyrpipe?

Thanks again

Vic

El 10 jun 2022, a las 21:19, Urminder Singh ***@***.******@***.***>> escribió:



ATENCIÓN: Este mensaje proviene de una fuente EXTERNA a UFV. Por favor, sea cuidadoso especialmente con los enlaces y los archivos adjuntos que contenga.



Hi Vic,
This is because by default pyrpipe assumes each fastq is in its own directory and salmon output gets written to:

<workdir>/<SRRid_directory>/salmon_out/quant.sf

Since your fastqs are all in the same directory, the quant.sf gets overwritten.

The easiest solution is to separate fastq in their respective directories.

Another way is that you can explicitly use the Salmon object to start quantification and provide the outdir.

for srrid in runlist:
    srrobject=sra.SRA(srrid,directory=workdir).trim(tgalore)
    thisout=<path_for_salmon_out_for_current_srrid>
    # explicitly call perform_quant
    salmon.perform_quant(srrobject,outdir=thisout)


Note the difference is, that instead of using syntactic sugar this is explicitly passing the SRA object to Salmon object's perform_quant<https://pyrpipe.readthedocs.io/en/latest/pyrpipe.html?highlight=quant#pyrpipe.quant.Salmon.perform_quant> method. This is also what happens under the hood when SRA.quant() is called. Currently, there is no way to forward kwargs from SRA.quant() to Salmon.perform_quant() - something I could improve in future releases.

Please let me know if this solves your issue.
Thanks

**Comment by urmi-21** [comment]
Hi Vic, 
Stringtie is used for transcript assembly, I am not sure which part of stringtie you want to replace with HTSeq. However, it is possible to integrate any tool in the pipeline. You could either write custom functions to use HTSeq library or [build an API](https://pyrpipe.readthedocs.io/en/latest/tutorial/api.html) extending pyrpipe's runnable class to execute any executable tool. 
Hope this helps!

Thank you

**Comment by victorsanchezarevalo** [comment]
Hi,
I have been able to run the pipeline completely using StringTie as transcript assembler, thank you very much for your help. I was planning to use HTSeq to generate the matrix count from the bam files. Maybe built an API would be the best option but I don have enough experience. How do I install HTSeq in pyrpipe?
Thanks again.
Vic

**Comment by urmi-21** [comment]
Hi @victorsanchezarevalo 
HTSeq is available as a python library and you could [install](https://htseq.readthedocs.io/en/master/install.html) it in the same conda environment as prypipe. Then you should be able to use pyrpipe together with HTSeq in python.
Hope this helps.
