### ISSUE TITLE
cannot change the output dir for stringtie merge

### ISSUE THREAD

**Issue by lijing28101** [urmi-21/pyrpipe#3]
After running stringtie for each sample, I want to merge the gtf by stringtie merge. But the output was written to a SRR folder, not the working folder, and the name has `SRR1573523_hisat2_sorted_stringtie` prefix, which cannot change
```
st.stringtie_merge(*tuple(gtfList),out_suffix="maizeMerged",**{"-p":"16"})
```

**Comment by urmi-21** [comment]
I have now added the parameter `out_dir` to the stringtie_merge function. If no out_dir is specified, merged file will be written in the same directory as the first input file. 51e27aaafce2c0833b9142636c112587e87f98a8
